name: Publish Storybook to GitHub Pages
# From Storybook tutorial for deploying to GitHub Pages: https://storybook.js.org/docs/sharing/publish-storybook#github-pages

on:
  push:
    branches: [ "main" ]

env:
  NODE_VERSION: '20.x'

jobs:
  deploy:
    permissions:
      contents: read
      pages: write
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - name: Manual Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
      
      - name: Build and deploy Storybook to GitHub Pages
        uses: bitovi/github-actions-storybook-to-github-pages@v1.0.3
        with:
          checkout: false
          install_command: npm ci
          build_command: npm run build-storybook
          path: storybook-static
